#!/usr/bin/env bash
# Configuration To Setting Up Server Nginx and listen to 80
# Serve page with "Hello World!"

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx restart
