#!/usr/bin/env bash
# configure Nginx server to redirect /redirect_me with a "301 Moved Permanently"

ADD301_REDIRECT="\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo apt-get update
sudo apt-get install -y nginx

mkdir /etc/nginx/html

echo "Hello World!" | sudo tee /etc/nginx/html/index.html > /dev/null

sudo sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-available/default

sudo service nginx restart
