#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page "301 Status" 


ADD301_REDIRECT="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo apt-get update
sudo apt-get install -y nginx
sudo mkdir /etc/nginx/html
sudo echo "Hello World!" > /etc/nginx/html/index.html
sudo sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-available/default
sudo service nginx restart
