#!/usr/bin/env bash
# Configures a new Ubuntu machine

# Update package information and install Nginx on web-01 server
apt-get -y update
apt-get -y install nginx

# Add a custom response header to identify the server for debugging
HOST_NAME=$(hostname)
HEADER="\\\n\tadd_header X-Served-By $HOST_NAME;\n"
FIND=$(grep "X-Server-by" /etc/nginx/sites-available/default)
if [[ -z $FIND ]]; then
    sed -i "23i $HEADER" /etc/nginx/sites-available/default
fi

# Create an initial index.html page
echo "Hello World!" > /var/www/html/index.html

# Add a redirection to another page in the Nginx configuration file
FIND=$(grep "redirect_me" /etc/nginx/sites-available/default)
STRING="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=3MbaGJN2ioQ;\n\t}\n"
if [[ -z $FIND ]]; then
    sed -i "42i $STRING" /etc/nginx/sites-available/default
fi

# Add a custom error page (404) to the Nginx configuration file
FIND=$(grep "error_page 404" /etc/nginx/sites-available/default)
ERROR="\\\n\terror_page 404 /custom_404.html;\n"
if [[ -z $FIND ]]; then
    echo "This is not the page you're looking for" > /var/www/html/custom_404.html
    sed -i "40i $ERROR" /etc/nginx/sites-available/default
fi

# Restart the Nginx service to apply the changes
service nginx restart

