#!/usr/bin/env bash
# Adjusts the web server configuration to run Nginx as the 'nginx' user on port 8080.

# Set the user in the Nginx configuration by replacing '#user' and its value.
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Replace port 80 with 8080 in the default site configuration.
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Provide read and write permissions to the owner for the Nginx configuration file.
chmod 644 /etc/nginx/nginx.conf

# Check for and terminate the Apache2 process to avoid interference with Nginx.
pkill apache2

# Start the Nginx service with the updated configuration using the 'nginx' user.
sudo -u nginx service nginx start
